### ISSUE TITLE
Translate Wiki to English, for contribution purposes

### ISSUE THREAD

**Issue by JohanG2012** [lan1dev/meta#1]

**Comment by rilind-h** [comment]
Jag kan hjälpa till med översättningen, men jag antar att jag behöver access för att kunna redigera den? :)

**Comment by JohanG2012** [comment]
Toppen :) Jag tror det ska gå, du borde kunna pusha upp en branch och sen skicka in en Pull Request (Kolla workflow i wikin om du inte vet hur) :)

**Comment by JohanG2012** [comment]
Git URLen för wikin är: https://github.com/lan1dev/meta.wiki.git

**Comment by rilind-h** [comment]
Okej, tackar. :)
