### ISSUE TITLE
Mockup #17 Required Fields

### ISSUE THREAD

**Issue by JohanG2012** [lan1dev/meta#10]
Which fields would make sense to have as required here?
![](https://raw.githubusercontent.com/wiki/lan1dev/meta/imgs/mockups/%2317%20Admin%20Dashboard%20-%20Create%20Tournament.png)

**Comment by JSudden** [comment]
Anser att Namn på turnering, Bild och Textboxen ska vara required.

**Comment by Wiktorsson** [comment]
Adding what time the tournamet will begin would be good aswell.
