### ISSUE TITLE
Mockup #20 Required Fields

### ISSUE THREAD

**Issue by JohanG2012** [lan1dev/meta#11]
Which fields would make sense to have as required here?
![](https://raw.githubusercontent.com/wiki/lan1dev/meta/imgs/mockups/%2320%20Admin%20Dashboard%20-%20Create%20LAN-Event.png)

**Comment by Wiktorsson** [comment]
Name required
Header image not required
Date not required if editing the event will be possible
Amount of Places required
Location required
Add tournaments required
Choose Ticket Type not required
Description required
